- name: install and run
  hosts: web
  tasks:
    - name: install nginx
      ansible.builtin.package: 
       - name: nginx
         state: present
      ansible.builtin.service:
       - name: nginx
         state: started
         enable: yes
        